spring.application.name=msc-memories
# Server Port
server.port=8080

# Neon Database Connection
spring.datasource.url=jdbc:postgresql://ep-sparkling-king-ayzpx2y8-pooler.c-5.us-east-2.aws.neon.tech/MSC%20MEMORIES?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_9YbQZyCc5evl
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# Cloudinary Storage Configuration
#cloudinary.cloud-name=your_cloud_name
#cloudinary.api-key=your_api_key
#cloudinary.api-secret=your_api_secret


cloudinary.cloud-name=deezwk7ue
cloudinary.api-key=755625539187524
cloudinary.api-secret=LurGq4AQuXLSeRgkSV1ilbYNFoI
# Max File Size Limits for Uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
logging.level.org.springframework.security=DEBUG



# Email related code here
# Email Configuration (e.g., Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=msccsau@gmail.com
spring.mail.password=hyvw saqa morj qmye
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
